name: GitInsight
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - requests
  - gitpython
  - pandas
  - sqlalchemy
  - scikit-learn
  - umap-learn
  - pip:
    - bidict
    - fastapi
    - uvicorn
    - -ftfy
    - crontab

